// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.3.1
// // LVGL version: 8.2.0
// // Project name: SquareLine_Project

// #include "ui.h"
// #include "ui_helpers.h"
// #include "TREY.h"
// ///////////////////// VARIABLES ////////////////////

// // void switch_to_main_ui(lv_timer_t * timer);

// // SCREEN: ui_Screen1
// void ui_Screen1_screen_init(void);
// lv_obj_t *ui_Screen1;
// lv_obj_t *ui_Panel2;
// lv_obj_t *ui_CoolDown;
// lv_obj_t *ui_eXPOSURE;
// lv_obj_t *ui_radiationDanger;
// lv_obj_t *ui_battery0;
// lv_obj_t *ui_battery25;
// lv_obj_t *ui_battery50;
// lv_obj_t *ui_Image75;
// lv_obj_t *ui_battery100;
// lv_obj_t *ui_Panel1;
// lv_obj_t *ui_Labelstatus;
// lv_obj_t *ui_labelKv;
// lv_obj_t *ui_labelCurrent;
// lv_obj_t *ui_Panel4;
// lv_obj_t *ui_labelmS;
// lv_obj_t *ui_labelTimer;
// lv_obj_t *ui____initial_actions0;
// const lv_img_dsc_t *ui_imgset_battery_[4] = {&ui_img_battery_0_png, &ui_img_battery_25_png, &ui_img_battery_50_png, &ui_img_battery_75_png};

// ///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
// #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP != 1
// #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
// #endif

// ///////////////////// ANIMATIONS ////////////////////

// ///////////////////// FUNCTIONS ////////////////////

// ///////////////////// SCREENS ////////////////////

// // void ui_init(void)
// // {
// //     lv_disp_t *dispp = lv_disp_get_default();
// //     lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
// //                                               false, LV_FONT_DEFAULT);
// //     lv_disp_set_theme(dispp, theme);
// //     ui_Screen1_screen_init();
// //     ui____initial_actions0 = lv_obj_create(NULL);
// //     lv_disp_load_scr(ui_Screen1);

// //     lv_obj_t *logo = lv_img_create(lv_scr_act());
// //     lv_img_set_src(logo, &TREY);
// //     lv_obj_center(logo);
// // }

// lv_obj_t *splash_logo;
// void switch_to_main_ui(lv_timer_t * timer)
// {
//     // Clear the current screen (logo screen)
//     lv_obj_clean(lv_scr_act());

//     // Load your main UI screen
//     ui_Screen1_screen_init();  // You may already have this
//     lv_scr_load(ui_Screen1);   // Show your main screen
// }

// void switch_to_main_ui(lv_timer_t * timer);


// void ui_init(void)
// {
//     lv_disp_t *dispp = lv_disp_get_default();
//     // lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_GREY), lv_palette_main(LV_PALETTE_RED),
//     //                                           false, LV_FONT_DEFAULT);
//     // lv_disp_set_theme(dispp, theme);

//     lv_theme_t *theme = lv_theme_default_init(
//     dispp,
//     lv_palette_main(LV_PALETTE_DEEP_ORANGE),  // Primary (for accents like the orange dot)
//     lv_palette_main(LV_PALETTE_BLUE_GREY),    // Secondary (to harmonize with navy tone)
//     false,
//     LV_FONT_DEFAULT
// );



//     // Create Splash Screen
//     lv_obj_t *splash_screen = lv_obj_create(NULL);

//     lv_obj_set_style_bg_color(splash_screen, lv_color_white(), 0); //set background colour to white

//     splash_logo = lv_img_create(splash_screen);
//     lv_img_set_src(splash_logo, &TREY);
//     lv_obj_center(splash_logo);

//     lv_scr_load(splash_screen); // Load the splash screen

//     // Set a timer to switch after 2 seconds (2000 ms)
//     lv_timer_create(switch_to_main_ui, 5000, NULL);
// }





#include "ui.h"
#include "ui_helpers.h"
#include "TREY.h"

// Global pointer for splash logo
lv_obj_t *splash_logo;
lv_obj_t *splash_screen;

// Forward declare function to avoid 'undeclared' error
void switch_to_main_ui(lv_timer_t * timer);

// // SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_CoolDown;
lv_obj_t *ui_eXPOSURE;
lv_obj_t *ui_radiationDanger;
lv_obj_t *ui_battery0;
lv_obj_t *ui_battery25;
lv_obj_t *ui_battery50;
lv_obj_t *ui_Image75;
lv_obj_t *ui_battery100;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Labelstatus;
lv_obj_t *ui_labelKv;
lv_obj_t *ui_labelCurrent;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_labelmS;
lv_obj_t *ui_labelTimer;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_battery_[4] = {&ui_img_battery_0_png, &ui_img_battery_25_png, &ui_img_battery_50_png, &ui_img_battery_75_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

// Your main screen objects (as per SquareLine)
lv_obj_t *ui_Screen1;
void ui_Screen1_screen_init(void);

// Switch from logo to GUI screen
void switch_to_main_ui(lv_timer_t * timer)
{
    lv_obj_clean(lv_scr_act());         // Clear logo screen
    ui_Screen1_screen_init();           // Initialize GUI screen
    lv_scr_load(ui_Screen1);            // Load GUI screen
}

// UI Init
void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_RED),
                                              lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // Create splash screen
    splash_screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(splash_screen, lv_color_white(), 0);  // White background

	lv_timer_handler(); /*let the GUI do its work */ // Call this to update LVGL and process timers

    // Add the logo
    splash_logo = lv_img_create(splash_screen);
    lv_img_set_src(splash_logo, &TREY);
    lv_obj_center(splash_logo);

	lv_timer_handler(); /*let the GUI do its work */ // Call this to update LVGL and process timers

    // Load splash screen
    lv_scr_load(splash_screen);

    //  Set timer to move to main screen after 3 sec
    lv_timer_create(switch_to_main_ui, 3000, NULL);
}


