// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x5432AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0xF6F6F6), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1, LV_BLEND_MODE_NORMAL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 310);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -86);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xB6B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolDown = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_CoolDown, &ui_img_thermometer_png);
    lv_obj_set_width(ui_CoolDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolDown, -46);
    lv_obj_set_y(ui_CoolDown, 0);
    lv_obj_set_align(ui_CoolDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CoolDown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CoolDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_eXPOSURE = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_eXPOSURE, &ui_img_radiation_warning_png);
    lv_obj_set_width(ui_eXPOSURE, 35);
    lv_obj_set_height(ui_eXPOSURE, 35);
    lv_obj_set_x(ui_eXPOSURE, -46);
    lv_obj_set_y(ui_eXPOSURE, 0);
    lv_obj_set_align(ui_eXPOSURE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eXPOSURE, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_eXPOSURE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_radiationDanger = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_radiationDanger, &ui_img_exposure_png);
    lv_obj_set_width(ui_radiationDanger, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_radiationDanger, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_radiationDanger, -117);
    lv_obj_set_y(ui_radiationDanger, 0);
    lv_obj_set_align(ui_radiationDanger, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_radiationDanger, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_radiationDanger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery0 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_battery0, &ui_img_battery_0_png);
    lv_obj_set_width(ui_battery0, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_battery0, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_battery0, 124);
    lv_obj_set_y(ui_battery0, 0);
    lv_obj_set_align(ui_battery0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery25 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_battery25, &ui_img_battery_25_png);
    lv_obj_set_width(ui_battery25, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_battery25, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_battery25, 123);
    lv_obj_set_y(ui_battery25, 0);
    lv_obj_set_align(ui_battery25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery25, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery50 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_battery50, &ui_img_battery_50_png);
    lv_obj_set_width(ui_battery50, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_battery50, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_battery50, 124);
    lv_obj_set_y(ui_battery50, 0);
    lv_obj_set_align(ui_battery50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery50, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image75 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image75, &ui_img_battery_75_png);
    lv_obj_set_width(ui_Image75, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image75, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image75, 124);
    lv_obj_set_y(ui_Image75, 0);
    lv_obj_set_align(ui_Image75, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image75, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image75, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery100 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_battery100, &ui_img_battery_full_png);
    lv_obj_set_width(ui_battery100, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_battery100, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_battery100, 124);
    lv_obj_set_y(ui_battery100, 0);
    lv_obj_set_align(ui_battery100, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery100, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery100, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 310);
    lv_obj_set_height(ui_Panel1, 160);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 33);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelstatus = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Labelstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelstatus, -83);
    lv_obj_set_y(ui_Labelstatus, -39);
    lv_obj_set_align(ui_Labelstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelstatus, "STANDBY");
    lv_obj_set_style_text_font(ui_Labelstatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelKv = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_labelKv, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_labelKv, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_labelKv, -85);
    lv_obj_set_y(ui_labelKv, 17);
    lv_obj_set_align(ui_labelKv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelKv, "50KV");
    lv_obj_set_style_text_align(ui_labelKv, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelKv, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelCurrent = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_labelCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCurrent, -87);
    lv_obj_set_y(ui_labelCurrent, 48);
    lv_obj_set_align(ui_labelCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCurrent, "5mA");
    lv_obj_set_style_text_font(ui_labelCurrent, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel4, 158);
    lv_obj_set_height(ui_Panel4, 104);
    lv_obj_set_x(ui_Panel4, 68);
    lv_obj_set_y(ui_Panel4, -5);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xEEEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0xB6B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xB5AAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelmS = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_labelmS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelmS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelmS, 49);
    lv_obj_set_y(ui_labelmS, 6);
    lv_obj_set_align(ui_labelmS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelmS, "mAs");
    lv_obj_set_style_text_color(ui_labelmS, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelmS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelmS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimer = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_labelTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimer, -22);
    lv_obj_set_y(ui_labelTimer, -2);
    lv_obj_set_align(ui_labelTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimer, "5.0");
    lv_obj_set_style_text_font(ui_labelTimer, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
